### ISSUE TITLE
Support for Azure Cosmos DB ODBC driver

### ISSUE THREAD

**Issue by MedAnd** [ww198643/Dapper.Extensions#2]
Hi,

Wondering if this Dapper extension supports Azure Cosmos DB via the [Azure Cosmos DB ODBC driver](https://docs.microsoft.com/en-us/azure/cosmos-db/odbc-driver)?

Thx.

**Comment by ww198643** [comment]
Supported, but you must first install the  Azure Cosmos DB ODBC driver.
